### ISSUE TITLE
Use options.cwd when reading a file, or not

### ISSUE THREAD

**Issue by shinnn** [sindresorhus/vinyl-file#2]
Currently this module doesn't use `options.cwd` when reading a file.

```js
vinylFile.readSync('bar.txt', {cwd: 'foo'}); // reads data from bar.txt
```

When I used this module first, I expected it to read a file from `foo/bar.txt`, not `bar.txt`. Which behavior do you think is more appropriate?

**Comment by floatdrop** [comment]
My bad. According to readme:

```js
var file = vinylFile.readSync('index.js');

console.log(file.path);
//=> /Users/sindresorhus/dev/vinyl-file/index.js
```

vinyl-file resolves path relative to current cwd (as `path.resolve` function does) - so `opts.cwd` should override this (or readme should explicitly say, that cwd will be ignored).
