### ISSUE TITLE
Can't create a vinyl file from a directory

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/vinyl-file#4]
I tried to parse an array of files and directories to vinyl files, but apparently it's not possible to parse a directory to a vinyl file with this library.

Or you open to a PR or should we create a new module that uses this module and supports directories as well?

**Comment by sindresorhus** [comment]
Do another module that depends on this. `vinyl-read` is available on npm. Yours could use `globby` to support glob patterns too. Would be happy to link to yours in the readme.

-

*Would be happy to accept a PR promisifying the API here to make it easier to make your module.*
