### ISSUE TITLE
[BUG/FEATURE-REQUEST] Async version of reading a file with ENOENT

### ISSUE THREAD

**Issue by bitbay** [sindresorhus/vinyl-file#7]
It's possible that i missed a "how-to" regarding this, but while the sync method seems to throw an error on _non-existent_ files (can detect with the not-so-elegant try-catch), the async use-case **seems to fail silently**.

I tried with (standard?) promises "resolveFn", "rejectFn" format like:
```
vinylFile.read(filePath).then( file => {
  console.log('file read');
}, err => {
  console.log('error');
});
```
But it's a no-go.

**Comment by SamVerschueren** [comment]
Can't reproduce here. Both the examples shows the ENOENT.

```js
'use strict';
const vinylFile = require('vinyl-file');

vinylFile.read('foo.txt')
	.then(data => {
		console.log(data);
	})
	.catch(err => {
		console.error(err);	
	});
```

```js
'use strict';
const vinylFile = require('vinyl-file');

vinylFile.read('foo.txt')
	.then(data => {
		console.log(data);
	}, err => {
		console.error(err);
	});
```

> { Error: ENOENT: no such file or directory, stat '/Users/sam/Projects/playground/vinyl-file-test/foo.txt'
>     at Error (native)
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'stat',
>   path: '/Users/sam/Projects/playground/vinyl-file-test/foo.txt' }

**Comment by bitbay** [comment]
Must have been some caching issue with my IDE...
Thanks for the quick reply!
