### ISSUE TITLE
Include TS types

### ISSUE THREAD

**Issue by Silic0nS0ldier** [sindresorhus/vinyl-file#9]
Currently types for this package can be sourced from DefinitelyTyped, however they are out of date. I'm happy to get them updated (matching semantics of other sindresorhus ESM packages which include types, e.g. https://github.com/sindresorhus/debounce-fn).

If however maintainers are open to including types in the package, I'm happy to put a PR together.

<details>
<summary>Module declaration types for v4</summary>

```ts
declare module "vinyl-file" {
    import File from "vinyl";

    export interface VinylFileOptions {
        /** Specifies the working directory the folder is relative to */
        cwd?: string | undefined;

        /** Specifies the folder relative to the cwd */
        base?: string | undefined;

        /** Setting this to false will retuurn file.contents as a stream */
        buffer?: boolean | undefined;

        /** Setting this to false will return file.contents as null and not read the file at all */
        read?: boolean | undefined;
    }

    export function vinylFileSync(path: string, options?: VinylFileOptions): File;

    export function vinylFile(path: string, options?: VinylFileOptions): Promise<File>;
}
```

</details>

**Comment by sindresorhus** [comment]
Sure. It should follow https://github.com/sindresorhus/typescript-definition-style-guide and the doc comments for the options should be sourced from the current readme docs.
